apiVersion: apps/v1
kind: Deployment
metadata:
  name: ak-web-app-poc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ak-web-app
  template:
    metadata:
      labels:
        app: ak-web-app
    spec:
      containers:
      - name: ak-web-app
        image: limarktest/webapp:latest
        ports:
        - containerPort: 8080
        
# service type loadbalancer       
---
apiVersion: apps/v1
kind: Service
metadata:
  name: ak-web-svc
spec:
  selector:
    app: ak-web-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer